### PR TITLE
Add generators

### PR DESCRIPTION
**Pull request by donnguyen**
Thanks guys for such a great gem! 🎉

This PR is just to add 2 generators: publisher and subscriber to make dev life a bit easier.

Cheers

### CODE REVIEW

**Comment by alachaum** [comment]
@donnguyen Thanks for the contribution. Looks great. I'll do a couple of tests locally and merge when good :)

**Comment by alachaum** [comment]
@donnguyen rubocop is in the red. I think running a quick `rubocop -a` should fix the build. I'll merge once the build is green 🍏 😄

**Comment by donnguyen** [comment]
@alachaum I have just corrected all rubocop offenses. Cheers

**Review by alachaum — APPROVED** [review]
👍

**Pull request merged**
